<?php
// code et tuto trouvé sur https://openclassrooms.com/courses/concevez-votre-site-web-avec-php-et-mysql/creer-des-images-en-php

// On indique que c'est une image qui est envoyée (ici png mais ça peut être jpeg aussi si photo par exemple)
header ("Content-type: image/png");
// On créé l'image avec 600 de large et 400 de haut
$destination = imagecreatefromjpeg("http://alexandreblin.ovh/FireEmblemStrategicApp/static/img/background.jpg");

// On charge d'abord les images
$source = imagecreatefrompng("http://alexandreblin.ovh/FireEmblemStrategicApp/static/img/character_portrait/Cordelia_portrait.png");
// Les fonctions imagesx et imagesy renvoient la largeur et la hauteur d'une image
$largeur_source = imagesx($source);
$hauteur_source = imagesy($source);
$largeur_destination = imagesx($destination);
$hauteur_destination = imagesy($destination);

// On veut placer le portrait du personnage à gauche en haut
$destination_x = 0;
$destination_y = 0;

// On définit juste la couleur noire pour imagestring
$noir = imagecolorallocate($destination, 0, 0, 0);
// Ceci créé une chaîne de caractères avec le nom du personnage
imagestring($destination, 5, 320, 15, "Cordelia", $noir);

// Un rectangle noir se créé qui accueillera les talents
ImageRectangle ($destination, 180, 50, 610, 120, $noir);



// On met le portrait dans l'image de destination (la carte du personnage)
imagecopy($destination, $source, $destination_x, $destination_y, 0, 0, $largeur_source, $hauteur_source);

imagepng($destination);

// if($_POST){
//   // On récupère les datas venant de l'ajax de builder.min.js
//   $build = $_POST['build'];
//   $myfile = fopen("[".$build[0]."] ".$build[1].".txt", "w") or die("Unable to open file!");
//
//   // Petite trad
//   // $build[0] = nom du personnage
//   // $build[1] = nom du build ou date du jour si non renseigné
//
//   // /!\ Si on met aucun talent ni nom la ça marche
//
//   // On écrit le nom et tous les talents du perso "\r\n" permet de sauter une ligne (voir https://stackoverflow.com/questions/15130289/php-fwrite-new-line)
//   fwrite($myfile,"Nom : ".$build[0]."\r\n"."\r\n"."");
//   fwrite($myfile,"Talent 1 : ".$build[2]."\r\n".$build[3]."\r\n"."\r\n"."");
//   fwrite($myfile,"Talent 2 : ".$build[4]."\r\n".$build[5]."\r\n"."\r\n"."");
//   fwrite($myfile,"Talent 3 : ".$build[6]."\r\n".$build[7]."\r\n"."\r\n"."");
//   fwrite($myfile,"Talent 4 : ".$build[8]."\r\n".$build[9]."\r\n"."\r\n"."");
//   fwrite($myfile,"Talent 5 : ".$build[10]."\r\n".$build[11]."");
//   fwrite($myfile, ""."\r\n"."-------------------------------------------"."\r\n"."Generated by Fire Emblem Strategic App"."\r\n"."http://alexandreblin.ovh/FireEmblemStrategicApp/pages/characterbuilder.html"."");
//   fclose($myfile);
// }
?>
