<?php
if($_POST){
  // On récupère les datas venant de l'ajax de builder.min.js
  $build = $_POST['build'];
  $myfile = fopen("[".$build[0]."] ".$build[1].".txt", "w") or die("Unable to open file!");

  // Petite trad
  // $build[0] = nom du personnage
  // $build[1] = nom du build ou date du jour si non renseigné

  // /!\ Si on met aucun talent ni nom la ça marche

  // On écrit le nom et tous les talents du perso "\r\n" permet de sauter une ligne (voir https://stackoverflow.com/questions/15130289/php-fwrite-new-line)
  fwrite($myfile,"Nom : ".$build[0]."\r\n"."\r\n"."");
  fwrite($myfile,"Talent 1 : ".$build[2]."\r\n".$build[3]."\r\n"."\r\n"."");
  fwrite($myfile,"Talent 2 : ".$build[4]."\r\n".$build[5]."\r\n"."\r\n"."");
  fwrite($myfile,"Talent 3 : ".$build[6]."\r\n".$build[7]."\r\n"."\r\n"."");
  fwrite($myfile,"Talent 4 : ".$build[8]."\r\n".$build[9]."\r\n"."\r\n"."");
  fwrite($myfile,"Talent 5 : ".$build[10]."\r\n".$build[11]."");
  fwrite($myfile, ""."\r\n"."-------------------------------------------"."\r\n"."Generated by Fire Emblem Strategic App"."\r\n"."https://alexandreblin.ovh/FireEmblemStrategicApp/pages/characterbuilder.html"."");
  fclose($myfile);
}
?>
